import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Welcome from '@/components/Welcome'
import { GetServerSideProps } from 'next'
import axios from 'axios'
import { baseURL } from '@/baseURl'
import { post } from '@/@types/@types'
import { useEffect } from 'react'
import { formatMongoDate } from '@/utils/utilsDate'

const inter = Inter({ subsets: ['latin'] })

interface Props{
  formattedPosts: post[];
}
export default function Home({formattedPosts}:Props) {
  
  console.log(formattedPosts)
  
  return (
    <>
      <Head>
      <title>Msodoki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
      <Welcome posts={formattedPosts}/>
      </div>
    </>
  )
}


export const getServerSideProps:GetServerSideProps = async()=>{
  const {data} = await axios.get<post[]>(`${baseURL}/posts`,{
    withCredentials: true
  })
 
  const formattedPosts = data.map((post) => ({
    ...post,
    formattedDate: formatMongoDate(post.createdAt),
  }));
  return {
    props:{formattedPosts}
  }
}